#!/bin/bash
lock=fsnipp-tmux-lock
buffer=fsnipp-tmux-buffer

tmux wait -L $lock
tmux deleteb -b $buffer 2> /dev/null
tmux new-window -n "fsnipp" "fsnipp | tmux loadb -b $buffer - ; tmux wait -U $lock"

tmux wait -L $lock
tmux wait -U $lock

tmux paste-buffer -b $buffer 2> /dev/null
exit 0
